import { PieceTypeEnum } from "@/interfaces";

export const CONSTANTS = {
  BOX_SIZE: 0.0657,
  BOX_SPACE: 0.0657,
  BOX_MOVE: 0.657,
  CAMERA_POSITION: [0.01, 14, 8] as [x: number, z: number, y: number],
  PIECES: {
    DIRECTIONS: {
      [PieceTypeEnum.empty]: [],
      [PieceTypeEnum.pawn]: [
        [0, 1],
        [1, 1],
        [1, 0],
        [1, -1],
        [0, -1],
        [-1, -1],
        [-1, 0],
        [-1, 1],
      ],
      [PieceTypeEnum.horse]: [
        [1, 2],
        [2, 1],
        [2, -1],
        [1, -2],
        [-1, -2],
        [-2, -1],
        [-2, 1],
        [-1, 2],
      ],
      [PieceTypeEnum.bishop]: [
        [0, 0],
        [1, 1],
        [0, 0],
        [1, -1],
        [0, 0],
        [-1, -1],
        [0, 0],
        [-1, 1],
      ],
      [PieceTypeEnum.rook]: [
        [0, 1],
        [1, 0],
        [0, -1],
        [-1, 0],
      ],
      [PieceTypeEnum.queen]: [
        [0, 1],
        [1, 1],
        [1, 0],
        [1, -1],
        [0, -1],
        [-1, -1],
        [-1, 0],
        [-1, 1],
      ],
      [PieceTypeEnum.king]: [
        [0, 1],
        [1, 1],
        [1, 0],
        [1, -1],
        [0, -1],
        [-1, -1],
        [-1, 0],
        [-1, 1],
      ],
    },
  },
  OPENINGS: {
    a3: "Anderssen's Opening",
    h3: "Clemenz Opening",
    Na3: "Sodium Attack",
    Nh3: "Amar Opening",
    g4: "Grob's Attack",
    f3: "Barnes Opening",
    e3: "Van't Kruijs Opening",
    d3: "Mieses Opening",
    c3: "Saragossa Opening",
    e4: "King's Pawn Opening",
    d4: "Queen's Pawn Opening",
    c4: "English Opening",
    Nf3: "Zukertort Opening",
    f4: "Bird Opening",
    b3: "Larsen's Opening",
    g3: "King's Fianchetto Opening",
    Nc3: "Dunst Opening",
    b4: "Polish Opening",
    "e4|e5": "Open Game",
    "e4|c5": "Sicilian Defense",
    "e4|e6": "French Defense",
    "e4|c6": "Caro-Kann Defense",
    "e4|d6": "Pirc Defense",
    "e4|d5": "Scandinavian Defense",
    "e4|g6": "Modern Defense",
    "e4|Nc6": "Nimzowitsch Defense",
    "e4|b6": "Owen's Defense",
    "e4|Nf6": "Alekhine Defense",
    "d4|d5": "Closed Game",
    "d4|Nf6": "Indian Game",
    "d4|d5|c4": "Queen's Gambit",
    "d4|Nf6|c4|e6": "Queen's Gambit Declined",
    "d4|Nf6|c4|g6": "King's Indian Defense",
    "d4|Nf6|c4|e6|Nc3|Bb4": "Nimzo-Indian Defense",
    "d4|Nf6|c4|e6|Nf3|b6": "Queen's Indian Defense",
    "d4|d5|c4|c6": "Slav Defense",
    "d4|d5|c4|e6": "Queen's Gambit Declined",
    "d4|d5|c4|c5": "Modern Benoni",
    "d4|Nf6|c4|c5": "Benoni Defense",
    "d4|Nf6|c4|c5|d5": "Benko Gambit",
    "d4|Nf6|Nf3|g6|c4|Bg7": "King's Indian Defense: Fianchetto Variation",
    "e4|e5|Nf3|Nc6|Bb5": "Ruy Lopez",
    "e4|e5|Nf3|Nc6|Bc4": "Italian Game",
    "e4|e5|Nf3|Nc6|Bc4|Bc5": "Giuoco Piano",
    "e4|e5|Nf3|Nc6|Bc4|Bc5|b4": "Evans Gambit",
    "e4|e5|Nf3|Nc6|d4": "Scotch Game",
    "e4|e5|Nf3|Nc6|d4|exd4|Nxd4": "Scotch Game: Classical Variation",
    "e4|e5|Nf3|Nc6|Nc3": "Three Knights Game",
    "e4|e5|Nf3|Nc6|Bb5|a6|Ba4": "Ruy Lopez: Morphy Defense",
    "e4|e5|Nf3|Nc6|Bb5|a6|Ba4|Nf6": "Ruy Lopez: Closed",
    "e4|c5|Nf3|d6|d4|cxd4|Nxd4|Nf6|Nc3|a6": "Sicilian Defense: Najdorf",
    "e4|c5|Nf3|d6|d4|cxd4|Nxd4|Nf6|Nc3|g6": "Sicilian Defense: Dragon",
    "e4|c5|Nf3|Nc6|d4": "Sicilian Defense: Classical",
    "e4|c5|Nf3|Nc6|Bb5": "Sicilian Defense: Moscow Variation",
    "e4|c5|Nf3|d6|d4|cxd4|Nxd4|Nf6|Nc3|e6": "Sicilian Defense: Scheveningen",
    "e4|c5|Nf3|d6|d4|cxd4|Nxd4|Nf6|Nc3|a6|Be3|e5": "Sicilian Defense: Najdorf English Attack",
    "d4|Nf6|c4|e6|Nf3|d5|Nc3|Be7": "Queen's Gambit Declined: Orthodox",
    "d4|Nf6|c4|e6|Nf3|d5|cd5|ed5|Bg5": "QGD: Lasker Defense",
    "d4|Nf6|c4|e6|Nf3|d5|cd5|ed5|Bg5|h6|Bh4|c6": "QGD: Tartakower Defense",
  },
  BOARD: {
    INIT: [PieceTypeEnum.rook, PieceTypeEnum.horse, PieceTypeEnum.bishop, PieceTypeEnum.queen, PieceTypeEnum.king, PieceTypeEnum.bishop, PieceTypeEnum.horse, PieceTypeEnum.rook],
    PAWNS: [PieceTypeEnum.pawn, PieceTypeEnum.pawn, PieceTypeEnum.pawn, PieceTypeEnum.pawn, PieceTypeEnum.pawn, PieceTypeEnum.pawn, PieceTypeEnum.pawn, PieceTypeEnum.pawn],
  },
};
